import property_insights

property_insights.best_properties()
property_insights.best_budget_properties()
property_insights.best_location_properties()
property_insights.safest_properties()
property_insights.best_family_properties()
property_insights.best_hybrid_properties()